server:
  port: 9091

spring:
  application:
    name: VEHICLE-SERVICE
#  zipkin:
#    base-url: http://127.0.0.1:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.3:8761/eureka/
  instance:
    hostname: 172.17.0.3
